name: Build and push docker image

on:
  push:
    branches:
      - master
      - main

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get tag
        uses: jimschubert/query-tag-action@v1
        id: tagger
      - name: Show Tag
        run: |
          echo 'Output from Get Tag: ${{steps.tagger.outputs.tag}}'
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags:
      #       - ${{ github.repository_owner }}/fiber-app:latest
      #       - ${{ github.repository_owner }}/fiber-app:${{ env.RELEASE_VERSION }}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
